project_id = "suncgglbheilkeimwuxt"

[functions.chat-stream]
verify_jwt = false

[functions.upload-file]
verify_jwt = false

[functions.superjournal]
verify_jwt = false

[functions.journal]
verify_jwt = false