project_id = "suncgglbheilkeimwuxt"

[functions.chat-stream]
verify_jwt = true

[functions.upload-file]
verify_jwt = true

[functions.superjournal]
verify_jwt = true

[functions.journal]
verify_jwt = true

[functions.process-persona-upload]
verify_jwt = true

[functions.google-slides-test]
verify_jwt = true

[functions.artisan-cut-call2]
verify_jwt = true

[functions.abort-message-turn]
verify_jwt = true

[functions.google-slides-fetch]
verify_jwt = true