project_id = "suncgglbheilkeimwuxt"

[functions.chat-stream]
verify_jwt = true

[functions.upload-file]
verify_jwt = true

[functions.superjournal]
verify_jwt = true

[functions.journal]
verify_jwt = true

[functions.process-persona-upload]
verify_jwt = true

[functions.artisan-cut-extraction]
verify_jwt = true

[functions.google-auth-url]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.google-slides]
verify_jwt = true