-- Insert all 7 journal documents with complete content
INSERT INTO knowledge_entries (title, content, entry_type, source_file) VALUES 
(
  'Team Introduction & Context Letter', 
  E'Dear Gunnar, Kirby, Samara, and Stefan,\n\nWhat you''ll see in these journals and uploaded files are conversations. Don''t treat them as gospel. They''re exchanges I''ve had with you, and with Grok AI, to help me make sense of the founder path as I go.\n\nThat said: if I have stated something concrete - something I''ve done, decided, or committed to - take that part seriously.\n\nLove, Boss', 
  'journal', 
  'journal_Doc_1-2.md'
),
(
  'Market Validation & Sales Cofounder Strategy', 
  E'Boss: Asking if Grok''s long monologue made sense.\n\nGunnar: Mostly yes. Solid: UVAR wedge credible, SaaS/ARR logic sound, features practical, EIT/Horizon funding real, sales cofounder > tech cofounder. Weak: market sizing inflated, routing patent shaky, underestimates bureaucracy/GDPR, incumbents may move faster than assumed, exit multiples optimistic. Summary: UVAR = plausible niche, founder fit strong, but Grok mixes pragmatism with hype—separate structure from décor.\n\nBoss: Reflects on "ChatGPT killed my startup" meme. Worry: incumbents like HERE/TomTom can crush me. Is wedge big/defensible enough to go all-in?\n\nGunnar: AI-wrapper startups die because labs kill them with updates. Your wedge different: regulatory glue, domain scar tissue, B2B sales motion, acquisition logic. Incumbents can always crush, but question is incentive now. Worthy to go all-in if: validate Berlin demand in 3–6mo, focus on one painful workflow, add sales cofounder. Otherwise risk = hype graveyard.\n\nBoss: Realization—need sales cofounder, not tech. Focus: mid-tier subcontractor fleets, not cities or DHL. Worry: can I find sales person to commit life to scrappy startup?\n\nGunnar: Right anxiety. Sales killers w/ fleet experience usually comfy in corp roles. Likely candidates: mid-career BD managers wanting meaning, ex-consultants who know logistics cycles, rebound founders. Pitch to them: clear problem (€ fines), founder-market fit, early ARR path (€200k Y1), exit upside (5–7x ARR). Hard, but not impossible. Key: equity 20–30% needed for them to see it as mission, not just quota.', 
  'journal', 
  'journal_Doc_3-2.md'
),
(
  'Exit Strategy & Equity Planning', 
  E'Boss (2025-09-11): Objectives — [1] €100M exit by early 2029, [2] ≥70% proceeds to me. Ask: high-level strategy map for entire journey. Immediate paths: (1) form consortium, apply to EIT UM Strategic Innovation Open Call by Sep 23; (2) clear Antler interviews for Antler One starting Sep 23; (3) go solo with Berlin pilot without 1/2.\n\nGrok: Reality check on ownership. 70% at exit is unlikely. With a sales cofounder (~20% equity) and prudent dilution, target **35–45%** personal stake at €100M exit → **€35–45M** gross; with ~30% DE capital gains → **€25–30M** net. Use non-dilutive first, tight option pool, and negotiate secondaries later.\n\nBoss: Align on **40%** target as mental north star.\n\nGrok: Agreed. 2025 benchmarks (Carta/SaaStr) show solo EU mobility/regtech founders end 25–35% after 3–4 rounds; you can push **35–45%** by front-loading grants/pilots and capping investor ownership at **15–20%** total. At **€10M ARR**, EU SaaS multiples **8–10x** → **€80–100M** exit; line up acquirers early for secondary (sell 10–15%) without heavy dilution.\n\nStrategy guardrails:\n- **Equity**: Sales cofounder **15–20%**, 4-yr vest w/ cliff; ESOP **10–15%** max. Keep each round ≤**20%** dilution; tie sales cofounder''s vest to **€1M ARR** milestone.\n- **Financing**: Phase 1–2 via **non-dilutive** (EIT/Horizon, pilots). If needed, consider **revenue-based financing** to avoid equity hits.\n- **Milestones**: Hit **€2M ARR** self-funds growth; **€10M ARR** triggers exit conversations.\n- **Tactics now**: Execute Option 1 (consortium outreach) immediately; keep Option 2 (Antler) as credibility/bridge; Option 3 (Berlin pilot) runs regardless to prove paid demand.\n\nOutcome: North star = **€100M exit with ~40% personal stake**. Plan = minimize dilution early, convert grants/pilots to ARR, and build optionality for secondary + strategic exit.', 
  'journal', 
  'journal_Doc_4-2.md'
),
(
  'Professional Background & Experience', 
  E'Boss: Founder & Product Marketing leader, 19 yrs B2B SaaS & mobility. Edge = translating complex tech/regulation into GTM clarity. Current mission: Oovar → Europe''s UVAR compliance layer.\n\nExperience:\n\nOovar (Founder & CEO, Aug 2025– )\n- Building EU-wide fleet compliance: Risk-Check API, Permit Concierge, Ops Dashboard.\n- Berlin LEZ rule model + data pipeline → modular city coverage.\n- Driver discovery → reroutes, permit friction → MVP + pricing tests.\n- Pilots + EIT UM consortium outreach.\n\nAether AI (Founder, Feb 2024–Jul 2025)\n- Tackled AI session context-loss; built command console w/ persistent memory.\n- Positioned for technical teams needing long-session AI collaboration.\n\nTalkwalker (VP Product Marketing, Jun 2022–Jan 2024)\n- GTM strategy → contributed to acquisition.\n- Rebuilt messaging → +30% adoption growth.\n- Launched cross-functional plays lifting win rates.\n- Partnered CS to scale advanced use cases.\n\nHERE Technologies (Head of Product Marketing, Apr 2014–Mar 2022)\n- Launched 4 SaaS products (€18M+ CLV).\n- GTM for high-value shippers → €12M uplift.\n- Owned €36M pipeline T&L segment.\n- #1 market ranking x3 yrs.\n- Brand overhaul → +74% YoY recall.\n- Built 9-person PMM team, 100% retention.\n\nIBM (Lead Consultant, 2009–2012)\n- Price sensitivity + loyalty optimization for US retailer.\n\nAccenture (Business Analyst, 2007–2009)\n- Retail strategy: revenue levers, cost structures.\n\nHCL Technologies (Assoc Manager, 2006–2007)\n- Early cloud computing roadmap + GTM.\n\nEducation:\n- MBA, Oxford Saïd (2012–2013, full scholarship).\n- BSc IT, Mumbai University (2001–2004).', 
  'journal', 
  'journal_Doc_6-2.md'
);