// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzedghqnndqxvelmwwpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZWRnaHFubmRxeHZlbG13d3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzI1NTMsImV4cCI6MjA3MzQ0ODU1M30.0D_WzR2CNy7ZrYqiShJaQu4IAnz_nYgnDb1OjR5kx6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});